package com.adolfo.ui;

import com.adolfo.analizadores.Lexico;
import com.adolfo.analizadores.Parser;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hectoradolfo
 */
public class FramePrincipal extends javax.swing.JFrame {

    private String code;

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        setLayout(null);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCodigo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generador arbol de activacion procedimientos");

        jtaCodigo.setColumns(20);
        jtaCodigo.setRows(5);
        jScrollPane1.setViewportView(jtaCodigo);

        jLabel1.setText("INGRESE EL CODIGO.");

        jButton1.setText("GENERAR ARBOL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jButton1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        code = jtaCodigo.getText();

        if (!code.isEmpty()) {
            try {
                StringReader reader = new StringReader(code);
                Lexico lexico = new Lexico(reader);
                /*pide un archivo que tenga el codigo para leerlo*/
                Parser pa = new Parser(lexico);

                pa.parse();
                String arbol = pa.getArbol() + " \n }";
                graficar(arbol);
                JOptionPane.showMessageDialog(this, "COMPILO EXITOSAMENTE");
                
                Thread.sleep(3000);
                
                Runtime rt = Runtime.getRuntime();
                try {
                    //Esperamos medio segundo para dar tiempo a que la imagen se genere
                    rt.exec("nohup display arbol.jpg ");
                } catch (IOException ex) {
                    Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } catch (Exception e) {
                System.out.println("error " + e);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Tienes que escribir el codigo,"
                    + "\n para despues compilar");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void graficar(String arbol) {
        FileWriter fichero = null;
        PrintWriter escritor;
        try {
            fichero = new FileWriter("graf.dot");
            escritor = new PrintWriter(fichero);
            escritor.print(arbol);
        } catch (Exception e) {
            System.err.println("Error al escribir el archivo graf.dot");
        } finally {
            try {
                if (null != fichero) {
                    fichero.close();
                }
            } catch (Exception e2) {
                System.err.println("Error al cerrar el archivo graf.dot");
            }
        }
        try {
            Runtime rt = Runtime.getRuntime();
            rt.exec("dot -Tjpg -o arbol.jpg graf.dot");
        } catch (Exception ex) {
            System.err.println("Error al generar la imagen para el archivo "
                    + "graf.dot");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaCodigo;
    // End of variables declaration//GEN-END:variables
}
