
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.adolfo.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSP = 4;
  public static final int COMA = 5;
  public static final int PROGRAMA = 11;
  public static final int ENTERO = 14;
  public static final int NUMEROS = 10;
  public static final int EOF = 0;
  public static final int ID = 7;
  public static final int IGUAL = 6;
  public static final int error = 1;
  public static final int PUNTOCOMA = 8;
  public static final int PAREIN = 2;
  public static final int FUNCION = 12;
  public static final int BEGIN = 15;
  public static final int END = 13;
  public static final int PARAMETRO = 9;
  public static final int PAREOUT = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAREIN",
  "PAREOUT",
  "DOSP",
  "COMA",
  "IGUAL",
  "ID",
  "PUNTOCOMA",
  "PARAMETRO",
  "NUMEROS",
  "PROGRAMA",
  "FUNCION",
  "END",
  "ENTERO",
  "BEGIN"
  };
}

